// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	bot "github.com/allthingscode/gobot/internal/bot"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// Callbacks provides a mock function with given fields: ctx
func (_m *API) Callbacks(ctx context.Context) (<-chan bot.InboundCallback, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Callbacks")
	}

	var r0 <-chan bot.InboundCallback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan bot.InboundCallback, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan bot.InboundCallback); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bot.InboundCallback)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: ctx, msg
func (_m *API) Send(ctx context.Context, msg bot.OutboundMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bot.OutboundMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWithButtons provides a mock function with given fields: ctx, msg, buttons
func (_m *API) SendWithButtons(ctx context.Context, msg bot.OutboundMessage, buttons [][]bot.Button) error {
	ret := _m.Called(ctx, msg, buttons)

	if len(ret) == 0 {
		panic("no return value specified for SendWithButtons")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bot.OutboundMessage, [][]bot.Button) error); ok {
		r0 = rf(ctx, msg, buttons)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with no fields
func (_m *API) Stop() {
	_m.Called()
}

// Typing provides a mock function with given fields: ctx, chatID, threadID
func (_m *API) Typing(ctx context.Context, chatID int64, threadID int64) func() {
	ret := _m.Called(ctx, chatID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for Typing")
	}

	var r0 func()
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) func()); ok {
		r0 = rf(ctx, chatID, threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

// Updates provides a mock function with given fields: ctx, timeout
func (_m *API) Updates(ctx context.Context, timeout int) (<-chan bot.InboundMessage, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 <-chan bot.InboundMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (<-chan bot.InboundMessage, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) <-chan bot.InboundMessage); ok {
		r0 = rf(ctx, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bot.InboundMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
