// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	bot "github.com/allthingscode/gobot/internal/bot"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, sessionKey, msg
func (_m *Handler) Handle(ctx context.Context, sessionKey string, msg bot.InboundMessage) (string, error) {
	ret := _m.Called(ctx, sessionKey, msg)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bot.InboundMessage) (string, error)); ok {
		return rf(ctx, sessionKey, msg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bot.InboundMessage) string); ok {
		r0 = rf(ctx, sessionKey, msg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bot.InboundMessage) error); ok {
		r1 = rf(ctx, sessionKey, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleCallback provides a mock function with given fields: ctx, cb
func (_m *Handler) HandleCallback(ctx context.Context, cb bot.InboundCallback) error {
	ret := _m.Called(ctx, cb)

	if len(ret) == 0 {
		panic("no return value specified for HandleCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bot.InboundCallback) error); ok {
		r0 = rf(ctx, cb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
