// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PairingStorer is an autogenerated mock type for the PairingStorer type
type PairingStorer struct {
	mock.Mock
}

// GetOrCreateCode provides a mock function with given fields: chatID
func (_m *PairingStorer) GetOrCreateCode(chatID int64) (string, error) {
	ret := _m.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(chatID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAuthorized provides a mock function with given fields: chatID
func (_m *PairingStorer) IsAuthorized(chatID int64) (bool, error) {
	ret := _m.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthorized")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (bool, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = rf(chatID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPairingStorer creates a new instance of PairingStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairingStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairingStorer {
	mock := &PairingStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
